### PR TITLE
replace references to custom bibtex.js

### PR DESCRIPTION
**Pull request by maxheld83**
as of retorquere/zotero-better-bibtex#667 the Zotero Better Bibtex plugin supports `Local-Zo-Url-N` out of the box, so the (outdated?) custom `bibtex.js` herein may no longer be necessary.

Perhaps this is a better way of doing it, because ZBB updates their translator anyway, so this solves that problem and users may skip this additional step.

### CODE REVIEW

**Comment by maxheld83** [comment]
just to be sure – this *should* wait on a successful close of https://github.com/retorquere/zotero-better-bibtex/issues/667, I was a little bit trigger-happy here.

**Comment by pmcarlton** [comment]
Very happy to merge this when #667 above closes—and glad that anyone at all has found this script useful.

**Comment by maxheld83** [comment]
this has shipped in https://github.com/retorquere/zotero-better-bibtex/releases/tag/1.6.97 now, so I think it's safe to merge.

**Comment by maxheld83** [comment]
original issue is closed, this is ready for merge: https://github.com/retorquere/zotero-better-bibtex/issues/667

**Pull request merged**
